### ISSUE TITLE
Line 2 Serial

### ISSUE THREAD

**Issue by E3t1jump** [Engineering-3/RCM-Comm#2]
Per our recent use of Line 2 to connect to via TeraTerm to get log data from the xPico, and the concern Brian stated about not being able to connect the Line 2 jumpers on the RCM-Comm board AND attach the RCM-BFin:

Can we do any testing to verify if we might damage any of the boards by having both Line 1 and Line 2 active with the RCM-BFin attached? It may be that the only reason it worked when I tried it was because I had Line 2 set to Command? It would be nice to see if we might be able to run both serial lines of the xPico simultaneously (what options could this provide us?).

**Comment by E3t1jump** [comment]
There are two UART connectors on the RCMx1. UART 0 connects to the xPico Line 1 and UART 1 connects to the xPico Line 2. The RCM-BFin uses xPico Line 1 for its main communication link back to a PC and MainController and I was sending communication to the RCM-BFin through this connection while also connecting an FTDI to xPico Line 2 through the RCMx1 UART port. Did this not cause issues because there was no transmission from the RCM-BFin across Line 2? Other?

If we wanted to use Line 2 for an outside connection, should we trim the corresponding pins from the RCM-BFin to prevent issues? Only if we are using an FTDI?

I want to make sure we capture these notes here for reference.

**Comment by EmbeddedMan** [comment]
After a good phone call discussing options, Tim and I agreed that if we were to redo the existing COMM board (with it's EOLed WiFi module) with the two UART ports, we would add three sets of jumpers for the second UART to all any two of the following three sets of pins to connect : BFin, WiFi radio, RCMx1.

However, as the next generation of COMM boards will use the xPico 240 radio which only has one serial port, no jumpers are required in the next gen design, since the one serial port will be used for communication between the BFin and the PC via the WiFi module.

I'm going to close this issue, as there isn't anything more to be done, but it will remain here so that it can be searched for in the future if this history is required.
